# We specify the base image we need for our
# go application
FROM golang:1.12.0-alpine3.9
# We create an /app directory within our
# image that will hold our application source
# files
RUN mkdir /webapps
# We copy everything in the root directory
# into our /app directory
ADD . /webapps
# We specify that we now wish to execute 
# any further commands inside our /app
# directory
WORKDIR /webapps
# we run go build to compile the binary
# executable of our Go program

RUN go build -o http-try  .
# Our start command which kicks off
# our newly created binary executable

#expose on that port
EXPOSE 8000

# Command to run the executable
CMD ["./http-try "]